import pygame

from .rect import RectHitbox
from .types import F, FAble, Vec2f, Vec2fAble, Vec2i

class Camera:
    camerazoom: F
    maxzoom: F
    minzoom: F
    rendersize: Vec2f
    surface: pygame.Surface
    topleft: Vec2f

    def __init__(
        self,
        surface: pygame.Surface,
        topleft: Vec2fAble,
        rendersize: Vec2fAble,
        camerazoom: FAble,
    ) -> None: ...
    def set_zoom_limits(self, zoom_in: FAble, zoom_out: FAble) -> None: ...
    def translate(self, rel: Vec2fAble) -> None: ...
    @property
    def hitbox(self) -> RectHitbox: ...
    @property
    def camera_world_center(self) -> Vec2f: ...
    def set_camera_world_center(self, world: Vec2f) -> None: ...
    def zoom_with_focus(self, rel: FAble, focus: Vec2i) -> None: ...
    def zoom(self, rel: FAble) -> None: ...
    def distance_to_camera(self, distance: FAble) -> F: ...
    def distance_to_world(self, distance: FAble) -> F: ...
    def point_to_camera(self, pt: Vec2fAble) -> Vec2f: ...
    def point_to_world(self, pt: Vec2fAble) -> Vec2f: ...
