from abc import abstractmethod
from enum import Enum
from typing import Callable, Dict, TypeVar

from .types import Vec2fAble

class CollideResult(Enum):
    NO = ...
    YES = ...
    UNSURE = ...

    @staticmethod
    def for_sure(value: bool) -> CollideResult: ...
    def __bool__(self) -> bool: ...

AnyHitbox = TypeVar("AnyHitbox", bound="Hitbox")
CollisionMap = Dict[str, Callable[[AnyHitbox], CollideResult]]

class Hitbox:
    _collides_map: CollisionMap
    _contains_map: CollisionMap
    _variant: str

    def __init__(
        self, variant: str, collides_map: CollisionMap, contains_map: CollisionMap
    ) -> None: ...
    @staticmethod
    def none() -> Hitbox: ...
    @abstractmethod
    def contains_point(self, pt: Vec2fAble) -> CollideResult: ...
    def collides_hitbox(self, hitbox: Hitbox) -> CollideResult: ...
    def contains_hitbox(self, hitbox: Hitbox) -> CollideResult: ...
